// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_index from "./routes/api/index.ts";
import * as $bridge from "./routes/bridge.tsx";
import * as $faucet from "./routes/faucet.tsx";
import * as $index from "./routes/index.tsx";
import * as $bridge_ActionButton from "./islands/bridge/ActionButton.tsx";
import * as $bridge_ActiveForm from "./islands/bridge/ActiveForm.tsx";
import * as $bridge_AppContainer from "./islands/bridge/AppContainer.tsx";
import * as $bridge_CurrencyAmount from "./islands/bridge/CurrencyAmount.tsx";
import * as $bridge_Height from "./islands/bridge/Height.tsx";
import * as $bridge_LegalsPopup from "./islands/bridge/LegalsPopup.tsx";
import * as $bridge_control_from_Balance from "./islands/bridge/control/from/Balance.tsx";
import * as $bridge_control_from_Input from "./islands/bridge/control/from/Input.tsx";
import * as $bridge_control_from_Slip from "./islands/bridge/control/from/Slip.tsx";
import * as $bridge_control_from_mod from "./islands/bridge/control/from/mod.tsx";
import * as $bridge_control_mod from "./islands/bridge/control/mod.ts";
import * as $bridge_mod from "./islands/bridge/mod.ts";
import * as $common_Balance from "./islands/common/Balance.tsx";
import * as $common_ConnectionInfo from "./islands/common/ConnectionInfo.tsx";
import * as $common_Connector from "./islands/common/Connector.tsx";
import * as $common_FhChainPicker from "./islands/common/FhChainPicker.tsx";
import * as $common_ListInput from "./islands/common/ListInput.tsx";
import * as $common_Navbar from "./islands/common/Navbar.tsx";
import * as $common_Receiver from "./islands/common/Receiver.tsx";
import * as $common_TestIsland from "./islands/common/TestIsland.tsx";
import * as $common_Web3Input_Web3Input from "./islands/common/Web3Input/Web3Input.tsx";
import * as $common_menuButton from "./islands/common/menuButton.tsx";
import * as $common_mod from "./islands/common/mod.ts";
import * as $common_which_Which from "./islands/common/which/Which.tsx";
import * as $common_which_WhichCancel from "./islands/common/which/WhichCancel.tsx";
import * as $common_which_WhichChoice from "./islands/common/which/WhichChoice.tsx";
import * as $common_which_WhichChoices from "./islands/common/which/WhichChoices.tsx";
import * as $common_which_WhichSearch from "./islands/common/which/WhichSearch.tsx";
import * as $common_which_WhichTitle from "./islands/common/which/WhichTitle.tsx";
import * as $faucet_ActionButton from "./islands/faucet/ActionButton.tsx";
import * as $faucet_ActiveForm from "./islands/faucet/ActiveForm.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/index.ts": $api_index,
    "./routes/bridge.tsx": $bridge,
    "./routes/faucet.tsx": $faucet,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/bridge/ActionButton.tsx": $bridge_ActionButton,
    "./islands/bridge/ActiveForm.tsx": $bridge_ActiveForm,
    "./islands/bridge/AppContainer.tsx": $bridge_AppContainer,
    "./islands/bridge/CurrencyAmount.tsx": $bridge_CurrencyAmount,
    "./islands/bridge/Height.tsx": $bridge_Height,
    "./islands/bridge/LegalsPopup.tsx": $bridge_LegalsPopup,
    "./islands/bridge/control/from/Balance.tsx": $bridge_control_from_Balance,
    "./islands/bridge/control/from/Input.tsx": $bridge_control_from_Input,
    "./islands/bridge/control/from/Slip.tsx": $bridge_control_from_Slip,
    "./islands/bridge/control/from/mod.tsx": $bridge_control_from_mod,
    "./islands/bridge/control/mod.ts": $bridge_control_mod,
    "./islands/bridge/mod.ts": $bridge_mod,
    "./islands/common/Balance.tsx": $common_Balance,
    "./islands/common/ConnectionInfo.tsx": $common_ConnectionInfo,
    "./islands/common/Connector.tsx": $common_Connector,
    "./islands/common/FhChainPicker.tsx": $common_FhChainPicker,
    "./islands/common/ListInput.tsx": $common_ListInput,
    "./islands/common/Navbar.tsx": $common_Navbar,
    "./islands/common/Receiver.tsx": $common_Receiver,
    "./islands/common/TestIsland.tsx": $common_TestIsland,
    "./islands/common/Web3Input/Web3Input.tsx": $common_Web3Input_Web3Input,
    "./islands/common/menuButton.tsx": $common_menuButton,
    "./islands/common/mod.ts": $common_mod,
    "./islands/common/which/Which.tsx": $common_which_Which,
    "./islands/common/which/WhichCancel.tsx": $common_which_WhichCancel,
    "./islands/common/which/WhichChoice.tsx": $common_which_WhichChoice,
    "./islands/common/which/WhichChoices.tsx": $common_which_WhichChoices,
    "./islands/common/which/WhichSearch.tsx": $common_which_WhichSearch,
    "./islands/common/which/WhichTitle.tsx": $common_which_WhichTitle,
    "./islands/faucet/ActionButton.tsx": $faucet_ActionButton,
    "./islands/faucet/ActiveForm.tsx": $faucet_ActiveForm,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
